#!/bin/bash
set -x

# install bower
if [ ! -d $OPENSHIFT_NODEJS_DIR/node_modules/bower ]
then
    cd $OPENSHIFT_NODEJS_DIR
    npm install bower
fi

cd $OPENSHIFT_REPO_DIR
HOME=$OPENSHIFT_DATA_DIR bower install
